title: Bill blog post
author: billmallet
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog project description.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  billmallet # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
